In [33]:
!pip install numpy pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in /home/student/.local/lib/python3.10/site-packages (1.24.3)
Requirement already satisfied: pandas in /home/student/.local/lib/python3.10/site-packages (2.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/student/.local/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Requirement already satisfied: tzdata>=2022.1 in /home/student/.local/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0
[notice] To update, run: python3.10 -m pip install --upgrade pip

In [34]:
ls

Preprocessing.ipynb  SDNFlow_Dataset_attack.csv  SDNFlow_Dataset_Normal.csv

In [35]:
import numpy as np
import pandas as pd

### Data Preprocessing

In [36]:
df = pd.read_csv('SDNFlow_Dataset_Normal.csv')

In [37]:
df.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6,22,41410,6.472,113472,628,...,0.0,113472,7295988,628,6659,628,1,10,0,SSH
1,2,2048,192.168.56.1,192.168.56.201,6,41410,22,6.465,24492,370,...,0.0,26080,24492,381,370,370,2,1,0,SSH
2,3,2048,192.168.56.203,192.168.56.201,1,0,0,4.798,2211,4,...,0.0,28291,3799,385,15,0,3,2,0,ICMP
3,4,2048,192.168.56.201,192.168.56.203,17,57426,1236,595.270,10827817,25627,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,STREAMING
4,5,2048,192.168.56.201,192.168.56.203,17,48549,1234,595.251,154551644,114704,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,STREAMING

In [38]:
df.shape

(221564, 39)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221564 entries, 0 to 221563
Data columns (total 39 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   flow_ID                221564 non-null  int64
 1   eth_type               221564 non-null  int64
 2   ipv4_src               221564 non-null  object
 3   ipv4_dst               221564 non-null  object
 4   ip_proto               221564 non-null  int64
 5   src_port               221564 non-null  int64
 6   dst_port               221564 non-null  int64
 7   flow_duration          221564 non-null  float64
 8   tot_len_pkts           221564 non-null  int64
 9   tot_pkts               221564 non-null  int64
 10  flow_byts_s            221564 non-null  float64
 11  flow_pkts_s            221564 non-null  float64
 12  pkt_size_average       221564 non-null  float64
 13  fwd_header_len         221564 non-null  int64
 14  Byts_max_interval_2s   221564 non-null  int64
 15  Byts_min_interval_2s   221564 non-null  int64
 16  Byts_mean_interval_2s  221564 non-null  float64
 17  Byts_std_interval_2s   221564 non-null  float64
 18  Pkts_max_interval_2s   221564 non-null  int64
 19  Pkts_mean_interval_2s  221564 non-null  float64
 20  Pkts_min_interval_2s   221564 non-null  int64
 21  Pkts_std_interval_2s   221564 non-null  float64
 22  active_max             221564 non-null  int64
 23  active_mean            221564 non-null  float64
 24  active_min             221564 non-null  int64
 25  active_std             221564 non-null  float64
 26  idle_max               221564 non-null  int64
 27  idle_mean              221564 non-null  float64
 28  idle_min               221564 non-null  int64
 29  idle_std               221564 non-null  float64
 30  TnBPDstIP              221564 non-null  int64
 31  TnBPSrcIP              221564 non-null  int64
 32  TnPPDstIP              221564 non-null  int64
 33  TnPPSrcIP              221564 non-null  int64
 34  TnPPerDport            221564 non-null  int64
 35  Tn_FlowsPDstIP         221564 non-null  int64
 36  Tn_FlowsPSrcIP         221564 non-null  int64
 37  Attack                 221564 non-null  int64
 38  Category               221564 non-null  object
dtypes: float64(12), int64(24), object(3)
memory usage: 65.9+ MB

In [40]:
df.isnull().sum()

flow_ID                  0
eth_type                 0
ipv4_src                 0
ipv4_dst                 0
ip_proto                 0
src_port                 0
dst_port                 0
flow_duration            0
tot_len_pkts             0
tot_pkts                 0
flow_byts_s              0
flow_pkts_s              0
pkt_size_average         0
fwd_header_len           0
Byts_max_interval_2s     0
Byts_min_interval_2s     0
Byts_mean_interval_2s    0
Byts_std_interval_2s     0
Pkts_max_interval_2s     0
Pkts_mean_interval_2s    0
Pkts_min_interval_2s     0
Pkts_std_interval_2s     0
active_max               0
active_mean              0
active_min               0
active_std               0
idle_max                 0
idle_mean                0
idle_min                 0
idle_std                 0
TnBPDstIP                0
TnBPSrcIP                0
TnPPDstIP                0
TnPPSrcIP                0
TnPPerDport              0
Tn_FlowsPDstIP           0
Tn_FlowsPSrcIP           0
Attack                   0
Category                 0
dtype: int64

In [41]:
df['Category'].unique()

array(['SSH', 'ICMP', 'STREAMING', 'DNS', 'HTTP', 'FTP', 'NTP'],
      dtype=object)

In [42]:


df['eth_type'].unique().size

1

drop eth_type

In [43]:
df['ipv4_src'].unique().size

3083

In [44]:
to_drop = []
for i in df.columns:
    counts = df[i].unique().size
    print(f"{i} size : {counts}")
    if counts == 1:
        to_drop.append(i)

flow_ID size : 221564
eth_type size : 1
ipv4_src size : 3083
ipv4_dst size : 3115
ip_proto size : 3
src_port size : 22369
dst_port size : 21964
flow_duration size : 18047
tot_len_pkts size : 16118
tot_pkts size : 1118
flow_byts_s size : 105626
flow_pkts_s size : 53855
pkt_size_average size : 28509
fwd_header_len size : 1239
Byts_max_interval_2s size : 14111
Byts_min_interval_2s size : 9050
Byts_mean_interval_2s size : 25389
Byts_std_interval_2s size : 26875
Pkts_max_interval_2s size : 867
Pkts_mean_interval_2s size : 2768
Pkts_min_interval_2s size : 403
Pkts_std_interval_2s size : 6976
active_max size : 89
active_mean size : 250
active_min size : 78
active_std size : 264
idle_max size : 10
idle_mean size : 322
idle_min size : 10
idle_std size : 491
TnBPDstIP size : 22390
TnBPSrcIP size : 24957
TnPPDstIP size : 8239
TnPPSrcIP size : 4399
TnPPerDport size : 3373
Tn_FlowsPDstIP size : 201
Tn_FlowsPSrcIP size : 223
Attack size : 1
Category size : 7

In [45]:
to_drop

['eth_type', 'Attack']

In [46]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in /home/student/.local/lib/python3.10/site-packages (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /home/student/.local/lib/python3.10/site-packages (from scikit-learn) (1.24.3)
Requirement already satisfied: scipy>=1.5.0 in /home/student/.local/lib/python3.10/site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /home/student/.local/lib/python3.10/site-packages (from scikit-learn) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/student/.local/lib/python3.10/site-packages (from scikit-learn) (3.2.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0
[notice] To update, run: python3.10 -m pip install --upgrade pip

In [47]:
# from sklearn.preprocessing import OneHotEncoder

In [48]:
# ohe = OneHotEncoder()

In [49]:
from sklearn.preprocessing import LabelEncoder

In [50]:
le_catg = LabelEncoder()

In [51]:
df['Category'] = le_catg .fit_transform(df['Category'])

In [52]:
df.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6,22,41410,6.472,113472,628,...,0.0,113472,7295988,628,6659,628,1,10,0,5
1,2,2048,192.168.56.1,192.168.56.201,6,41410,22,6.465,24492,370,...,0.0,26080,24492,381,370,370,2,1,0,5
2,3,2048,192.168.56.203,192.168.56.201,1,0,0,4.798,2211,4,...,0.0,28291,3799,385,15,0,3,2,0,3
3,4,2048,192.168.56.201,192.168.56.203,17,57426,1236,595.270,10827817,25627,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,6
4,5,2048,192.168.56.201,192.168.56.203,17,48549,1234,595.251,154551644,114704,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,6

In [53]:
le_catg .classes_

array(['DNS', 'FTP', 'HTTP', 'ICMP', 'NTP', 'SSH', 'STREAMING'],
      dtype=object)

In [54]:
mapping_catg = dict(zip(le_catg .classes_,le_catg .transform(le_catg .classes_)))

In [55]:
le_catg .transform(['HTTP'])

array([2])

In [56]:
mapping_catg

{'DNS': 0, 'FTP': 1, 'HTTP': 2, 'ICMP': 3, 'NTP': 4, 'SSH': 5, 'STREAMING': 6}

In [57]:
df.head(-5)

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6,22,41410,6.472,113472,628,...,0.0,113472,7295988,628,6659,628,1,10,0,5
1,2,2048,192.168.56.1,192.168.56.201,6,41410,22,6.465,24492,370,...,0.0,26080,24492,381,370,370,2,1,0,5
2,3,2048,192.168.56.203,192.168.56.201,1,0,0,4.798,2211,4,...,0.0,28291,3799,385,15,0,3,2,0,3
3,4,2048,192.168.56.201,192.168.56.203,17,57426,1236,595.270,10827817,25627,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,6
4,5,2048,192.168.56.201,192.168.56.203,17,48549,1234,595.251,154551644,114704,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221554,221555,2048,8.43.72.98,192.168.56.203,6,443,46158,0.114,0,0,...,0.0,162706107,0,136042,0,0,161,3,0,2
221555,221556,2048,192.168.56.203,200.24.19.252,17,36103,53,0.320,77,1,...,0.0,4172,197595,27,1967,5,32,152,0,0
221556,221557,2048,200.24.19.252,192.168.56.203,17,53,36103,1.290,374,2,...,0.0,163711889,6183,136965,38,2,158,31,0,0
221557,221558,2048,192.168.56.203,200.24.19.252,17,39597,53,0.669,0,0,...,0.0,4172,197595,27,1967,5,32,152,0,0
221558,221559,2048,192.168.56.203,200.24.19.252,17,34519,53,0.666,0,0,...,0.0,4172,197595,27,1967,5,32,152,0,0

In [58]:
df2 = df.copy()
le_src = LabelEncoder()
le_dst = LabelEncoder()

In [59]:
df2['ipv4_src'] = le_src .fit_transform(df2['ipv4_src'])
df2['ipv4_dst'] = le_dst .fit_transform(df2['ipv4_dst'])

In [60]:
mapping_src  = dict(zip(le_src .classes_,le_src .transform(le_src .classes_)))

In [61]:
mapping_dest = dict(zip(le_dst .classes_,le_dst .transform(le_dst .classes_)))

In [62]:
df2.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,1484,1499,6,22,41410,6.472,113472,628,...,0.0,113472,7295988,628,6659,628,1,10,0,5
1,2,2048,1482,1501,6,41410,22,6.465,24492,370,...,0.0,26080,24492,381,370,370,2,1,0,5
2,3,2048,1486,1501,1,0,0,4.798,2211,4,...,0.0,28291,3799,385,15,0,3,2,0,3
3,4,2048,1484,1503,17,57426,1236,595.270,10827817,25627,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,6
4,5,2048,1484,1503,17,48549,1234,595.251,154551644,114704,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,6

In [64]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221564 entries, 0 to 221563
Data columns (total 39 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   flow_ID                221564 non-null  int64
 1   eth_type               221564 non-null  int64
 2   ipv4_src               221564 non-null  int64
 3   ipv4_dst               221564 non-null  int64
 4   ip_proto               221564 non-null  int64
 5   src_port               221564 non-null  int64
 6   dst_port               221564 non-null  int64
 7   flow_duration          221564 non-null  float64
 8   tot_len_pkts           221564 non-null  int64
 9   tot_pkts               221564 non-null  int64
 10  flow_byts_s            221564 non-null  float64
 11  flow_pkts_s            221564 non-null  float64
 12  pkt_size_average       221564 non-null  float64
 13  fwd_header_len         221564 non-null  int64
 14  Byts_max_interval_2s   221564 non-null  int64
 15  Byts_min_interval_2s   221564 non-null  int64
 16  Byts_mean_interval_2s  221564 non-null  float64
 17  Byts_std_interval_2s   221564 non-null  float64
 18  Pkts_max_interval_2s   221564 non-null  int64
 19  Pkts_mean_interval_2s  221564 non-null  float64
 20  Pkts_min_interval_2s   221564 non-null  int64
 21  Pkts_std_interval_2s   221564 non-null  float64
 22  active_max             221564 non-null  int64
 23  active_mean            221564 non-null  float64
 24  active_min             221564 non-null  int64
 25  active_std             221564 non-null  float64
 26  idle_max               221564 non-null  int64
 27  idle_mean              221564 non-null  float64
 28  idle_min               221564 non-null  int64
 29  idle_std               221564 non-null  float64
 30  TnBPDstIP              221564 non-null  int64
 31  TnBPSrcIP              221564 non-null  int64
 32  TnPPDstIP              221564 non-null  int64
 33  TnPPSrcIP              221564 non-null  int64
 34  TnPPerDport            221564 non-null  int64
 35  Tn_FlowsPDstIP         221564 non-null  int64
 36  Tn_FlowsPSrcIP         221564 non-null  int64
 37  Attack                 221564 non-null  int64
 38  Category               221564 non-null  int64
dtypes: float64(12), int64(27)
memory usage: 65.9 MB

In [65]:
df1 = df

In [66]:
for i in range df1['ipv4_src']:

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6,22,41410,6.472,113472,628,...,0.0,113472,7295988,628,6659,628,1,10,0,5
1,2,2048,192.168.56.1,192.168.56.201,6,41410,22,6.465,24492,370,...,0.0,26080,24492,381,370,370,2,1,0,5
2,3,2048,192.168.56.203,192.168.56.201,1,0,0,4.798,2211,4,...,0.0,28291,3799,385,15,0,3,2,0,3
3,4,2048,192.168.56.201,192.168.56.203,17,57426,1236,595.270,10827817,25627,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,6
4,5,2048,192.168.56.201,192.168.56.203,17,48549,1234,595.251,154551644,114704,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,6

In [68]:
df1['int_ip'] = df1['ipv4_src'].astype('str').str.replace('.','',regex="False").astype('int64')

ValueError: invalid literal for int() with base 10: ''

In [82]:
l = df1['ipv4_src'].size
for i in range(l):
    temp = df1['ipv4_src'][i]
    temp = temp.replace('.','')
    temp = temp.astype(int)
    df1['ipv4_src'][i] = temp

AttributeError: 'str' object has no attribute 'astype'

In [80]:
df1.head()

,flow_ID,eth_type,ipv4_src,ipv4_dst,ip_proto,src_port,dst_port,flow_duration,tot_len_pkts,tot_pkts,...,idle_std,TnBPDstIP,TnBPSrcIP,TnPPDstIP,TnPPSrcIP,TnPPerDport,Tn_FlowsPDstIP,Tn_FlowsPSrcIP,Attack,Category
0,1,2048,192.168.56.201,192.168.56.1,6,22,41410,6.472,113472,628,...,0.0,113472,7295988,628,6659,628,1,10,0,5
1,2,2048,192.168.56.1,192.168.56.201,6,41410,22,6.465,24492,370,...,0.0,26080,24492,381,370,370,2,1,0,5
2,3,2048,192.168.56.203,192.168.56.201,1,0,0,4.798,2211,4,...,0.0,28291,3799,385,15,0,3,2,0,3
3,4,2048,192.168.56.201,192.168.56.203,17,57426,1236,595.270,10827817,25627,...,0.0,188960322,180776253,157117,153898,30743,60,19,0,6
4,5,2048,192.168.56.201,192.168.56.203,17,48549,1234,595.251,154551644,114704,...,0.0,188960322,180776253,157117,153898,122654,60,19,0,6